# Generated by Django 3.1.2 on 2021-12-21 02:57

from django.db import migrations, models
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0129_add_product_types_and_attributes_perm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantChannelListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('product_class_qty', models.CharField(blank=True, max_length=250)),
                ('product_class_value', models.CharField(blank=True, max_length=250)),
                ('product_class_recommendation', models.CharField(blank=True, max_length=250)),
                ('updated_by', models.CharField(blank=True, max_length=250)),
                ('approved_by', models.CharField(blank=True, max_length=250)),
                ('approved_date', models.DateTimeField()),
            ],
            options={
                'ordering': ('product_class_qty',),
            },
        ),
    ]
