# Generated by Django 3.1.2 on 2021-12-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0130_productvariantchannellisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantchannellisting',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('SUBMITTED', 'submitted'), ('APPROVED', 'approved')], default='draft', max_length=60),
        ),
    ]
