# Generated by Django 3.1.2 on 2021-12-22 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0131_productvariantchannellisting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantchannellisting',
            name='approved_by',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantchannellisting',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantchannellisting',
            name='product_class_qty',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantchannellisting',
            name='product_class_recommendation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantchannellisting',
            name='product_class_value',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantchannellisting',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('approved', 'approved')], default='draft', max_length=60),
        ),
        migrations.AlterField(
            model_name='productvariantchannellisting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProductVariantChannelListings', to=settings.AUTH_USER_MODEL),
        ),
    ]
