# Generated by Django 3.1.2 on 2021-12-23 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0132_auto_20211222_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantchannellisting',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProductVariantChannelListing', to=settings.AUTH_USER_MODEL),
        ),
    ]
