# Generated by Django 3.1.2 on 2021-12-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_menu_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('content', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
