# Generated by Django 3.1.2 on 2021-12-02 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
